import type { PlatformIdentity } from '../contracts/PlatformIdentity';

export const platforms = [
  {
    id: 'taxi',
    domain: 'platform',
    label: 'Taxi',
    order: 1,
    initial: 'T',
    color: '#F4D03F',
    surfaceColor: '#F4D03F',
    onSurfaceColor: '#111111',
    aliases: ['Taxi'],
  },
  {
    id: 'uber',
    domain: 'platform',
    label: 'Uber',
    order: 2,
    initial: 'U',
    color: '#111111',
    surfaceColor: '#111111',
    onSurfaceColor: '#FFFFFF',
    aliases: ['Uber'],
  },
  {
    id: 'cabify',
    domain: 'platform',
    label: 'Cabify',
    order: 3,
    initial: 'C',
    color: '#7B2CBF',
    surfaceColor: '#7B2CBF',
    onSurfaceColor: '#FFFFFF',
    aliases: ['Cabify'],
  },
  {
    id: 'bolt',
    domain: 'platform',
    label: 'Bolt',
    order: 4,
    initial: 'B',
    color: '#22C55E',
    surfaceColor: '#22C55E',
    onSurfaceColor: '#111111',
    aliases: ['Bolt'],
  },
  {
    id: 'freeNow',
    domain: 'platform',
    label: 'Free Now',
    order: 5,
    initial: 'F',
    color: '#E53935',
    surfaceColor: '#E53935',
    onSurfaceColor: '#FFFFFF',
    aliases: ['Free Now', 'FreeNow'],
  },
  {
    id: 'other',
    domain: 'platform',
    label: 'Otra',
    order: 6,
    initial: 'O',
    color: '#9E9E9E',
    surfaceColor: '#9E9E9E',
    onSurfaceColor: '#111111',
    aliases: ['Otra', 'Other'],
  },
] as const satisfies readonly PlatformIdentity[];
