import type { ServiceTypeIdentity } from '../contracts/ServiceTypeIdentity';

export const serviceTypes = [
  {
    id: 'airport',
    domain: 'serviceType',
    label: 'Aeropuerto',
    order: 1,
    initial: 'A',
    icon: '✈️',
    aliases: ['Aeropuerto', 'Airport'],
  },
  {
    id: 'urban',
    domain: 'serviceType',
    label: 'Urbano',
    order: 2,
    initial: 'U',
    icon: '🏙️',
    aliases: ['Urbano', 'City'],
  },
  {
    id: 'station',
    domain: 'serviceType',
    label: 'Estación',
    order: 3,
    initial: 'E',
    icon: '🚉',
    aliases: ['Estación', 'Station'],
  },
  {
    id: 'booking',
    domain: 'serviceType',
    label: 'Reserva',
    order: 4,
    initial: 'R',
    icon: '📅',
    aliases: ['Reserva', 'Booking'],
  },
  {
    id: 'longDistance',
    domain: 'serviceType',
    label: 'Largo recorrido',
    order: 5,
    initial: 'L',
    icon: '🛣️',
    aliases: ['Largo recorrido', 'Long distance'],
  },
  {
    id: 'hospital',
    domain: 'serviceType',
    label: 'Hospital',
    order: 6,
    initial: 'H',
    icon: '🏥',
    aliases: ['Hospital'],
  },
  {
    id: 'frequentCustomer',
    domain: 'serviceType',
    label: 'Cliente habitual',
    order: 7,
    initial: 'C',
    icon: '⭐',
    aliases: ['Cliente habitual', 'Frequent customer'],
  },
  {
    id: 'parcel',
    domain: 'serviceType',
    label: 'Paquetería',
    order: 8,
    initial: 'P',
    icon: '📦',
    aliases: ['Paquetería', 'Parcel'],
  },
  {
    id: 'other',
    domain: 'serviceType',
    label: 'Otro',
    order: 9,
    initial: 'O',
    icon: '⋯',
    aliases: ['Otro', 'Other'],
  },
] as const satisfies readonly ServiceTypeIdentity[];
